spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: fsd-gateway
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000 
    
swagger.enabled: true
logging:
  config: classpath:logback-boot_dev.xml

apiurl:
  gatewayurl: http://localhost:8082

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    fsd-account:
      path: /account/**
      serviceId: fsd-account
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-auth:
      path: /auth/**
      serviceId: fsd-auth
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-course:
      path: /course/**
      serviceId: fsd-course
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-mentor:
      path: /mentor/**
      serviceId: fsd-mentor
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-payment:
      path: /payment/**
      serviceId: fsd-payment
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
      


---
spring:
  profiles: k8s
  application:
    name: fsd-gateway
server:
  port: 8082
  
    
eureka:
  client:
    service-url:
      defaultZone: http://fsd-registry:8081/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置
  

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000
    
swagger.enabled: true

apiurl:
  gatewayurl: http://fsd-gateway:8082

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    fsd-account:
      path: /account/**
      serviceId: fsd-account
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-auth:
      path: /auth/**
      serviceId: fsd-auth
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-course:
      path: /course/**
      serviceId: fsd-course
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-mentor:
      path: /mentor/**
      serviceId: fsd-mentor
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    fsd-payment:
      path: /payment/**
      serviceId: fsd-payment
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers